# Generated by nexus-theme-set — do not edit directly, edit the source theme's
# colors.toml instead. Re-run `nexus theme set <name>` to regenerate.
[colors]
background={{ background_strip }}
foreground={{ foreground_strip }}
selection-background={{ selection_strip }}
selection-foreground={{ foreground_strip }}

regular0={{ darker_background_strip }}
regular1={{ red_strip }}
regular2={{ green_strip }}
regular3={{ yellow_strip }}
regular4={{ blue_strip }}
regular5={{ magenta_strip }}
regular6={{ cyan_strip }}
regular7={{ foreground_strip }}

bright0={{ muted_strip }}
bright1={{ bright_red_strip }}
bright2={{ bright_green_strip }}
bright3={{ bright_yellow_strip }}
bright4={{ bright_blue_strip }}
bright5={{ bright_magenta_strip }}
bright6={{ bright_cyan_strip }}
bright7={{ dim_foreground_strip }}
