# Generated by nexus-theme-set — do not edit directly, edit the source theme's
# colors.toml instead. Re-run `nexus theme set <name>` to regenerate.

background            {{ background }}
foreground             {{ foreground }}
selection_background   {{ selection }}
selection_foreground   {{ foreground }}
cursor                 {{ accent }}
cursor_text_color      {{ background }}

active_border_color    {{ accent }}
inactive_border_color  {{ muted }}

color0  {{ darker_background }}
color8  {{ muted }}
color1  {{ red }}
color9  {{ bright_red }}
color2  {{ green }}
color10 {{ bright_green }}
color3  {{ yellow }}
color11 {{ bright_yellow }}
color4  {{ blue }}
color12 {{ bright_blue }}
color5  {{ magenta }}
color13 {{ bright_magenta }}
color6  {{ cyan }}
color14 {{ bright_cyan }}
color7  {{ foreground }}
color15 {{ dim_foreground }}
