name = "Tokyo Night"
mode = "dark"

background = "#1a1b26"
dark_background = "#16161e"
darker_background = "#101014"
lighter_background = "#24283b"

foreground = "#c0caf5"
dim_foreground = "#a9b1d6"

accent = "#7aa2f7"
selection = "#33467c"
muted = "#565f89"

red = "#f7768e"
orange = "#ff9e64"
yellow = "#e0af68"
green = "#9ece6a"
cyan = "#7dcfff"
blue = "#7aa2f7"
magenta = "#bb9af7"
brown = "#a88f6e"

bright_red = "#f7768e"
bright_orange = "#ff9e64"
bright_yellow = "#e0af68"
bright_green = "#9ece6a"
bright_cyan = "#7dcfff"
bright_blue = "#7aa2f7"
bright_magenta = "#bb9af7"
bright_brown = "#a88f6e"
